### PR TITLE
Browser : Mark books with blocked tags

### PR DESCRIPTION
**Pull request by plive498**
**Implements Feature:** Mark Books with blocked tags.
<br />

Summary of changes in this PR:

- New feature to mark books with blocked tags.

- Works on hitomi, hentai2read, hdporncomics, multporn

<br />
@AVnetWS/admin-team

### CODE REVIEW

**Comment by RobbWatershed** [comment]
Looks nice, thanks a lot !

Could you explain to me why you created your own list of blocked tags (BROWSER_MARK_BLOCKED_LIST) while the app already has one (Preferences.Key.DL_BLOCKED_TAGS) ?

What's the difference between these two lists ?

**Comment by plive498** [comment]
The differences are where they are and used for
(under preferences-browser, preferences-download)
(marking books, blocking downloads)

But it might be better to share the variable because their meanings are same.

I'll make a new commit if you want.

**Comment by RobbWatershed** [comment]
Yes please. Marking books and blocking downloads should both be linked. Separating those will confuse users imo.

**Comment by plive498** [comment]
I made a new commit to share variable between two options.

**Comment by RobbWatershed** [comment]
Looks good ! Thanks man

**Pull request merged**
