### PR TITLE
Fix some deprecations

### PR DESCRIPTION
**Pull request by TacoTheDank**
Summary of changes in this PR:
- Fix ScrollerCompat deprecations in DragSelectTouchListener
- Fix onActivityResult deprecations

Additional commit notes for project team:
- onRequestPermissionsResult is also deprecated, but I didn't do that one because the implementation of permission requesting around the project was a bit confusing.

### CODE REVIEW

**Comment by RobbWatershed** [comment]
Sorry I didn't see that PR (gotta add PRs to our Discord webhook)

I'll get back to you soon about it. Thanks for submitting !

**Comment by RobbWatershed** [comment]
It all looks fine ! I'll test that and publish it in the next update.

Don't hesitate to submit other changes 🙃 

> onRequestPermissionsResult is also deprecated, but I didn't do that one because the implementation of permission requesting around the project was a bit confusing.

It is. I'm aware of it but haven't taken the time to cleanup / refactor that part.

**Comment by RobbWatershed** [comment]
PS : Please submit further PRs to the `dev` branch to make things easier 😉

**Comment by TacoTheDank** [comment]
Thanks!

**Pull request merged**
